version: "3"
services:
  login-app:
      container_name: api-server
      image: card-tool-api
      restart: always
      build: .
      ports:
        - "3000:3000"
      links:
        - mongo
  mongo:
        container_name: mongo
        image: mongo
        ports:
          - '27017:27017'